// Skill-discovery tools — the self-describing playbook layer.
//
// The package bundles a set of `tr-*.md` skill recipes under `skills/` plus an
// AGENTS.md operating guide at the package root. These tools expose that
// content directly on the tool surface so an agent discovers the platform's
// playbook at connection time — over stdio AND the hosted HTTP transport.
//
// IMPORTANT: the content is read from the EMBEDDED module (bundled-content.ts,
// generated by scripts/embed-content.mjs), NOT from disk. The hosted endpoint
// runs inside the portal, which bundles this package — after bundling a runtime
// `fs.readFile('../skills/…')` resolves into the portal's build output and
// fails with ENOENT, so disk reads crash list_skills/read_skill/read_guide on
// hosted. Embedded string lookups survive bundling. (The install-skills/init
// CLI still copies the physical files — but that only runs locally, where the
// files exist.)
//
// All three tools are pure in-memory lookups: no REST API, no API key, no site
// context — hence `noSite: true` (multi-site mode skips site_id for them).

import { z } from 'zod';
import { BUNDLED_SKILLS, BUNDLED_DOCS } from '../bundled-content.js';
import { ok, withErrorBoundary, type ToolDef } from './helpers.js';

/** The only names `read_skill` will resolve. Matches the `tr-*.md` convention
 *  and, by forbidding slashes/dots, doubles as input hygiene. */
export const SKILL_NAME_RE = /^tr-[a-z0-9-]+$/;

export interface SkillMeta {
  name: string;
  description: string;
}

/**
 * Pull `name:` / `description:` out of a skill file's YAML frontmatter.
 *
 * The frontmatter is a flat block we author by hand (two single-line keys),
 * so a deliberately tiny regex parse beats pulling in a YAML dependency.
 * Falls back to the given name when `name:` is absent and to an empty
 * description when `description:` is.
 */
export function parseSkillFrontmatter(markdown: string, fallbackName: string): SkillMeta {
  let name = fallbackName;
  let description = '';
  const fm = markdown.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/);
  if (fm) {
    const body = fm[1];
    const nameLine = body.match(/^name:\s*(.+?)\s*$/m);
    const descLine = body.match(/^description:\s*(.+?)\s*$/m);
    if (nameLine) name = nameLine[1].trim();
    if (descLine) description = descLine[1].trim();
  }
  return { name, description };
}

/** List the bundled skills (name + description) from the embedded content. */
export function listBundledSkills(): SkillMeta[] {
  return Object.keys(BUNDLED_SKILLS)
    .sort()
    .map((key) => parseSkillFrontmatter(BUNDLED_SKILLS[key]!, key));
}

/** Return one bundled skill's markdown by name. Rejects anything that isn't a
 *  `tr-<kebab>` name or isn't a known skill. */
export function readBundledSkill(name: string): string {
  if (!SKILL_NAME_RE.test(name)) {
    throw new Error(
      `invalid skill name "${name}" — expected tr-<kebab-case>, e.g. tr-new-site. Use list_skills to see available skills.`,
    );
  }
  const content = BUNDLED_SKILLS[name];
  if (content === undefined) {
    throw new Error(`skill "${name}" not found. Use list_skills to see available skills.`);
  }
  return content;
}

/** Return a bundled package doc by whitelisted key (`agents` | `readme`). */
export function readPackageDoc(key: string): string {
  const content = BUNDLED_DOCS[key];
  if (content === undefined) {
    throw new Error(`unknown guide "${key}". Available: ${Object.keys(BUNDLED_DOCS).join(', ')}.`);
  }
  return content;
}

export const skillTools: ToolDef[] = [
  {
    name: 'read_guide',
    description:
      "Return the full Typeroll agent guide (the bundled AGENTS.md): platform conventions, the data model in 90 seconds, common operations with worked recipes, safety boundaries, and the tool-family reference. Read it once at the start of a session for the complete operating context — especially on the hosted connector, where the file isn't on disk for the client to fold in. Pass doc='readme' for the package README instead. Pure in-memory read: no API key or site required.",
    inputSchema: {
      doc: z
        .enum(['agents', 'readme'])
        .optional()
        .describe("Which guide to return: 'agents' (default — the full operating briefing) or 'readme'."),
    },
    noSite: true,
    handler: withErrorBoundary(async (args) => ok(readPackageDoc(args.doc ?? 'agents'))),
  },
  {
    name: 'list_skills',
    description:
      'List the bundled Typeroll playbook skills (name + description). Call this EARLY — the moment the user wants to build, migrate, redesign, brand, or otherwise design a site — to discover the step-by-step recipe that fits (e.g. tr-new-site, tr-migrate-wp, tr-brand, tr-blog, tr-responsive), then read_skill the most relevant one before acting. Pure in-memory read: no API key and no site required, so it works on the hosted connector and stdio alike.',
    noSite: true,
    handler: withErrorBoundary(async () => {
      const skills = listBundledSkills();
      return ok({ skills, count: skills.length });
    }),
  },
  {
    name: 'read_skill',
    description:
      'Return the full markdown of one bundled skill by name (e.g. "tr-new-site"). Use it after list_skills to load the playbook for the task at hand. Pure in-memory read: no API key and no site required.',
    inputSchema: {
      name: z
        .string()
        .describe('Skill name without the .md extension, e.g. "tr-new-site". Must match /^tr-[a-z0-9-]+$/.'),
    },
    noSite: true,
    handler: withErrorBoundary(async (args) => ok(readBundledSkill(args.name))),
  },
];
