// Write-audit log for the public REST API.
//
// One doc per state-changing call (POST / PUT / PATCH / DELETE). GET reads
// are not logged — they'd 10× the cost and don't carry the "what changed"
// signal the audit log exists to capture.
//
// Stored under organizations/{orgId}/sites/{siteId}/api_audit/{auto-id}.
// Per-site lets the UI scope "show me the last 50 writes for this key"
// without scanning the org. The doc id is generated by the datastore.

import { paths } from '@typeroll/shared';
import { getStore } from './datastore';

export interface ApiAuditEntry {
  key_prefix: string;
  method: 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  status: number;
  ip?: string;
  user_agent?: string;
  ts: string;
  /** A short, redacted preview of the request body for debugging — first 200
   *  chars after JSON-stringifying. We deliberately don't log the full body
   *  to avoid storing secrets the customer might have pasted into the API. */
  body_preview?: string;
}

export function shouldAudit(method: string): boolean {
  return method === 'POST' || method === 'PUT' || method === 'PATCH' || method === 'DELETE';
}

/**
 * Persist one audit entry. Fire-and-forget — failures here must NOT affect
 * the actual response. Audit lag is acceptable; losing a customer's write
 * because the audit log was unavailable is not.
 */
export async function recordAudit(args: {
  orgId: string;
  siteId: string;
  keyPrefix: string;
  method: string;
  path: string;
  status: number;
  ip?: string;
  userAgent?: string;
  bodyPreview?: string;
}): Promise<void> {
  if (!shouldAudit(args.method)) return;
  try {
    const entry: ApiAuditEntry = {
      key_prefix: args.keyPrefix,
      method: args.method as ApiAuditEntry['method'],
      path: args.path,
      status: args.status,
      ip: args.ip,
      user_agent: args.userAgent,
      ts: new Date().toISOString(),
      body_preview: args.bodyPreview ? args.bodyPreview.slice(0, 200) : undefined,
    };
    await getStore().addDoc(paths.apiAudit(args.orgId, args.siteId), entry);
  } catch {
    /* swallow */
  }
}

export function previewBody(body: unknown): string | undefined {
  if (body == null) return undefined;
  try {
    const s = typeof body === 'string' ? body : JSON.stringify(body);
    return s;
  } catch {
    return undefined;
  }
}
