// Codegen: embed the bundled skills + guide docs into a TS module so the
// skill-discovery tools work WITHOUT reading from disk.
//
// Why: the hosted MCP endpoint runs inside the portal, which bundles this
// package with Vite. After bundling, `import.meta.url` points into the
// portal's build output, so a runtime `fs.readFile('../skills/…')` resolves
// to a path that doesn't exist (ENOENT) and list_skills/read_skill/read_guide
// crash on the hosted connector. Embedding the content as string constants
// makes the tools pure in-memory lookups that survive bundling — and works
// identically over stdio.
//
// Run `npm run gen` after editing skills/*.md, AGENTS.md, or README.md.
// The generated src/bundled-content.ts is committed; a vitest drift guard
// fails CI if it falls out of sync with the source files.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = path.join(root, 'skills');
const outFile = path.join(root, 'src', 'bundled-content.ts');

const skillFiles = (await fs.readdir(skillsDir))
  .filter((f) => f.startsWith('tr-') && f.endsWith('.md'))
  .sort();

const skills = {};
for (const f of skillFiles) {
  skills[f.replace(/\.md$/, '')] = await fs.readFile(path.join(skillsDir, f), 'utf8');
}

const docs = {
  agents: await fs.readFile(path.join(root, 'AGENTS.md'), 'utf8'),
  readme: await fs.readFile(path.join(root, 'README.md'), 'utf8'),
};

const banner =
  '// GENERATED by scripts/embed-content.mjs — do not edit by hand.\n' +
  '// Run `npm run gen` after changing skills/*.md, AGENTS.md, or README.md.\n' +
  '// Embedded so the skill/guide tools work when this package is bundled into\n' +
  '// the hosted portal (no runtime disk read). See scripts/embed-content.mjs.\n' +
  '/* eslint-disable */\n\n';

const body =
  `export const BUNDLED_SKILLS: Record<string, string> = ${JSON.stringify(skills, null, 2)};\n\n` +
  `export const BUNDLED_DOCS: Record<string, string> = ${JSON.stringify(docs, null, 2)};\n`;

await fs.writeFile(outFile, banner + body, 'utf8');
console.log(
  `embed-content: ${skillFiles.length} skills + ${Object.keys(docs).length} docs → ${path.relative(root, outFile)}`,
);
